# Generated by Django 5.1.1 on 2024-09-16 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appScout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(default=0)),
                ('carta', models.FloatField(default=0)),
                ('conto', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appScout.customuser')),
            ],
        ),
    ]
